### ISSUE TITLE
Emojis don't render in Element when posted from Mattermost

### ISSUE THREAD

**Issue by muratbayan** [mattermost/matrix-as-mm#10]
Steps to reproduce
* Write a message from Mattermost in a shared channel with Element and use any emoji, e.g. `:blush:`

Expected result
* Element should display the emoji correctly, but instead simply displays the markdown text `:blush:`

When posting from Element to Mattermost, the `:blush:` emoji gets rendered correctly like in here 😊

**Comment by janostgren** [comment]
**Estimation**
6 hours

**Comment by janostgren** [comment]
Emojis now rendered in Element
